# Generated by Django 5.1.3 on 2025-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
