# Generated by Django 5.1.3 on 2025-01-30 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productattributevalue_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='ProductAttributeValue',
            new_name='AttributeValue',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(to='product.attributevalue'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
