# Generated by Django 5.1.3 on 2024-12-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_order_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanager',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
