# Generated by Django 5.1.3 on 2024-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_branchmanager_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the company.', max_length=255, verbose_name='Company Name')),
                ('address', models.TextField(help_text='The physical or mailing address of the company.', verbose_name='Company Address')),
                ('contact_number', models.CharField(help_text='The primary phone number to contact the company.', max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, help_text="The company's email address.", max_length=254, null=True, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, help_text="The company's official website URL.", null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, help_text="Upload the company's logo (optional).", null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('description', models.TextField(blank=True, help_text='A brief description of the company (optional).', null=True, verbose_name='Description')),
                ('registration_number', models.CharField(blank=True, help_text="The company's official registration number (optional).", max_length=50, null=True, verbose_name='Registration Number')),
                ('tax_number', models.CharField(blank=True, help_text="The company's tax identification number (optional).", max_length=50, null=True, verbose_name='Tax Number')),
                ('company_type', models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('supplier', 'Supplier')], help_text='The type of the company (e.g., Client, Agent, Supplier).', max_length=10, verbose_name='Company Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the record was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
