# Generated by Django 5.1.3 on 2024-12-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the factory.', max_length=255, verbose_name='Factory Name')),
                ('location', models.CharField(help_text='The physical location or address of the factory.', max_length=255, verbose_name='Location')),
                ('established_date', models.DateField(help_text='The date when the factory was established.', verbose_name='Established Date')),
                ('owner_name', models.CharField(help_text='The full name of the factory owner.', max_length=255, verbose_name='Owner Name')),
                ('capacity', models.IntegerField(help_text='The production capacity of the factory (e.g., units per day).', verbose_name='Production Capacity')),
                ('contact_email', models.EmailField(help_text='The email address for contacting the factory.', max_length=254, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the factory is currently operational.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
                'ordering': ['name'],
            },
        ),
    ]
