# Generated by Django 5.1.3 on 2024-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='The production capacity of the factory (e.g., units per day).', null=True, verbose_name='Production Capacity'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='established_date',
            field=models.DateField(auto_now=True, help_text='The date when the factory was established.', verbose_name='Established Date'),
        ),
    ]
