# Generated by Django 5.1.3 on 2024-12-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='owner_name',
            field=models.CharField(blank=True, help_text='The full name of the factory owner.', max_length=255, null=True, verbose_name='Owner Name'),
        ),
    ]
