# Generated by Django 5.1.3 on 2024-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_factory_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, help_text='The production capacity of the factory (e.g., units per day).', null=True, verbose_name='Production Capacity'),
        ),
    ]
