# Generated by Django 5.1.3 on 2025-02-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_tax_alter_company_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
