# Generated by Django 5.1.5 on 2025-02-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='transaction_type',
            new_name='transaction_types',
        ),
    ]
