# Generated by Django 5.1.3 on 2025-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_transaction_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('SAR', 'SAR')], default='USD', max_length=3),
        ),
    ]
