# Generated by Django 5.1.3 on 2025-02-10 17:16

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_field_name='amount_currency', decimal_places=2, default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('SAR', 'SAR'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
    ]
