# Generated by Django 5.1.3 on 2025-02-10 18:10

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_transaction_currency_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('SAR', 'SAR'), ('USD', 'USD')], default='USD', editable=False, max_length=3)),
                ('debit', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('credit_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('SAR', 'SAR'), ('USD', 'USD')], default='USD', editable=False, max_length=3)),
                ('credit', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('SAR', 'SAR'), ('USD', 'USD')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('next_execution', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
            ],
        ),
    ]
